aws_region         = "eu-west-1"
project_name       = "fargate-demo"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
private_subnet_cidr= "10.0.2.0/24"
az-1               = "eu-west-1a"
az-2               = "eu-west-1b"
vpc_name           = "DemoVPC"